spring.application.name=ordermanagementapi
spring.datasource.url=jdbc:postgresql://localhost:5432/ordersdb
spring.datasource.password=123
spring.datasource.username=user
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE